import Head from 'next/head';
import Image from 'next/image';
import React, { useState } from 'react';
import { Form } from '../components/Form';

import styles from '../styles/Home.module.css';

export interface FormValues {
  [key: string]: string;
}

export function getStaticProps() {
  // pass initial contact
  return {
    props: {
      initialContacts: [
        {
          id: 1,
          firstName: 'Ian',
          lastName: 'De Guzman',
          email: 'ianbrdeguzman@gmail.com',
          avatar: 'https://github.com/ianbrdeguzman.png'
        }
      ]
    }
  };
}

export default function Home({ initialContacts }) {
  const [contacts, setContacts] = useState(initialContacts);
  const [formValues, setFormValues] = useState<FormValues>({
    id: contacts.length + 1,
    firstName: '',
    lastName: '',
    email: '',
    avatar: ''
  });

  console.log(formValues);

  return (
    <div className={styles.container}>
      <Head>
        <title>Next Prisma</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <aside className={styles.form}>
        <h2 className={styles.heading}>Add a Contact</h2>
        <Form
          onSubmit={(e) => {
            e.preventDefault();
            if (Object.keys(formValues).length === 0) return;
            for (const prop in formValues) {
              if (formValues[prop].length === 0) return;
            }
            setContacts([...contacts, formValues]);
          }}
          formValues={formValues}
          setFormValues={setFormValues}
        />
      </aside>
      <main className={styles.contacts}>
        <h2 className={styles.heading}>Contacts</h2>
        {contacts.map((c) => (
          <article key={c.id} className={styles.contact}>
            <Image
              src={c.avatar}
              blurDataURL={c.avatar}
              alt={`${c.firstName}${c.lastName}`}
              width={80}
              height={80}
              placeholder="blur"
              className={styles.avatar}
            />
            <div className={styles.info}>
              <p className={styles.name}>
                {c.firstName} {c.lastName}
              </p>
              <p className={styles.email}>{c.email}</p>
            </div>
          </article>
        ))}
      </main>
    </div>
  );
}
