import Head from 'next/head';
import React, { useState } from 'react';
import { Form } from '../components/Form';
import { prisma } from '../lib/prisma';
import { Contact } from '@prisma/client';

import styles from '../styles/Home.module.css';
import { ContactCard } from '../components/ContactCard';

async function saveContact(contact: Contact) {
  const response = await fetch('/api/contact', {
    method: 'POST',
    body: JSON.stringify(contact)
  });

  if (!response.ok) {
    throw new Error(response.statusText);
  }

  return await response.json();
}

export async function getServerSideProps() {
  const contacts = await prisma.contact.findMany();
  return {
    props: {
      initialContacts: contacts
    }
  };
}

export default function Home({ initialContacts }) {
  const [contacts, setContacts] = useState(initialContacts);
  const [formValues, setFormValues] = useState<Contact>({
    id: contacts.length + 1,
    firstName: '',
    lastName: '',
    email: '',
    avatar: ''
  });

  return (
    <div className={styles.container}>
      <Head>
        <title>Next Prisma</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <aside className={styles.form}>
        <h2 className={styles.heading}>Add a Contact</h2>
        <Form
          onSubmit={async (e) => {
            e.preventDefault();
            if (Object.keys(formValues).length === 0) return;
            for (const prop in formValues) {
              if (formValues[prop].length === 0) return;
            }
            const savedContact = await saveContact(formValues);
            setContacts([...contacts, savedContact]);
            e.target.reset();
          }}
          formValues={formValues}
          setFormValues={setFormValues}
        />
      </aside>
      <main className={styles.contacts}>
        <h2 className={styles.heading}>Contacts</h2>
        {contacts.map((c) => (
          <ContactCard key={c.id} {...c} />
        ))}
      </main>
    </div>
  );
}
